
database_url: "postgresql://devuser:devpass@localhost:5432/devdb"
s3:
  bucket_name: "vutest-0"
  aws_access_key_id: "04bd6bddfe71d987ca68fb6fe04d9d38"
  aws_secret_access_key: "0ac28580d50bb2dae1fc8b5fc1eb56159c70e6057645d0746de210ffa02382d7"
  region_name: "auto"
  public_url: "https://pub-4de729d2405d450d9f448d5c900b31b2.r2.dev"
  endpoint_url: "https://7c4a779e538610c2eade8254bdcb4d05.r2.cloudflarestorage.com" # Example for MinIO
oidc:
  client_id: "uvtest"
  client_secret: "vKhTjuauF8K6xKlrVNQjq1JOHLXo8ReO"
  server_metadata_url: "http://keycloack:8080/realms/master/.well-known/openid-configuration"
jwt:
  secret_key: "a-very-secret-key"
  algorithm: "HS256"
  access_token_expire_minutes: 30
frontend:
  url: "http://localhost:3001"
